services:
  starbound-server:
    image: didstopia/starbound-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "21025:21025"
      - "27015-27030:27015-27030"
      - "27036-27037:27036-27037"
      - "4380:4380"
      - "27000-27031:27000-27031"
    volumes:
      - starbound-data:/steamcmd/starbound:cached
      - starbound-steam:/app/.steam:cached

volumes:
  starbound-data:
  starbound-steam:
